
stages:
  - test

cache:
  paths:
  - ~/.cache/pip/

danger:
  stage: test
  image: ruby:2.2
  before_script:
  - bundle install
  script:
  - bundle exec danger

pytest:
  stage: test
  image: python:3.7
  before_script:
  - pip install -r requirements.txt
  script:
  - python -m pytest tests/ --disable-warnings
