image: python:3.7

cache:
  paths:
  - ~/.cache/pip/

test:
  before_script:
  - pip install -r requirements.txt
  script:
  - python -m pytest tests/ --cov=. --cov-report xml:coverage.xml --disable-warnings
  - python-codacy-coverage -r coverage.xml

