image: python:3.7

stages:
- danger
- pytest

cache:
  paths:
  - ~/.cache/pip/

danger:
  image: ruby:2.2
  before_script:
  - bundle install
  script:
  - bundle exec danger

pytest:
  before_script:
  - pip install -r requirements.txt
  script:
  - python -m pytest tests/ --disable-warnings
